# Generated by Django 4.2.7 on 2023-12-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("types", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="notice",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="board.categorytypes"
            ),
        ),
    ]
