# Generated by Django 4.2.7 on 2023-12-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_categorytypes_options_alter_notice_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media/documents"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
