# Generated by Django 4.2.7 on 2023-12-31 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_notice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
